version: "3"
services:
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWD}
    expose:
      - 6379
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWD}
    volumes:
      - ${MONGODB_LOCAL_VOLUME}:/data/db
    expose:
      - 27017
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - ${API_PORT}
    depends_on:
      - redis
      - mongo
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - api
